### PR TITLE
Add initial documentation for Next.js

### PR DESCRIPTION
**Pull request by pkafei**
Added the Outsmartly banner to README file. Links to OutSmartly website.

### CODE REVIEW

**Review by jayphelps — APPROVED** [review]

**Review by jayphelps — DISMISSED** [review]
I added a commit to correct s/OutSmartly/Outsmartly but otherwise LGTM. Feel free to merge if ready.

**Comment by pkafei** [comment]
@jayphelps 
Thanks for reviewing my PR! 

There are a few other changes I would like to implement before merging- for example, adding the vercel production deploy script to `package.json`.

**Comment by jayphelps** [comment]
@pkafei Okiedoke. I can review that commit once it's pushed. Alternatively, if it would still make sense as a follow up PR that works too

**Comment by jayphelps** [comment]
I just noticed that this might be missing the `export OUTSMARTLY_TOKEN=value` in their bash profile thing maybe?

**Comment by pkafei** [comment]
Working on that now. The Outsmartly token will be placed in the environmental variable section of the Vercel platform.

**Review by jayphelps — APPROVED** [review]

**Comment by jayphelps** [comment]
LGTM please merge when ready

**Pull request merged**
